### ISSUE TITLE
Why return a function?

### ISSUE THREAD

**Issue by popey456963** [regexhq/youtube-regex#10]
Possibly missing something, but it seems to me like:

```
module.exports = /(?:youtube\.com\/\S*(?:(?:\/e(?:mbed))?\/|watch\/?\?(?:\S*?&?v\=))|youtu\.be\/)([a-zA-Z0-9_-]{6,11})/g;
```

Would be a better solution and let you get the benefits of Node module caching.  Is there a reason you don't use it?

**Comment by tunnckoCore** [comment]
It was initial wanting. There are reasons, some not apply to all modules at @regexhq org, but most are functions. Consistency between them is one reason, another is that some of the packages has additional options. Actually all should be updated to have options.

As about caching... If you want regex caching you may try @jonschlinkert's [regex-cache](https://github.com/jonschlinkert/regex-cache). He is performance and cache optimizations maniac/guru :)

**Comment by jonschlinkert** [comment]
> Would be a better solution 

In JavaScript, when the `g` flag is used with regular expressions, the [lastIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex) is updated when a match is found (with `.exec`, for example). 

All of the modules on the regexhq org return a function to ensure that the `.lastIndex` is always reset when the function is called. 

> let you get the benefits of Node module caching. 

On the contrary. Node.js always caches requires the first time they're called (using `require()`, which effectively wraps `Module._load`), regardless of what's exported. 

> Is there a reason you don't use it?

Yes. Since Node.js effectively creates a "singleton-like" instance for all of the modules loaded by `require()` across a project, by exporting a function as the main export (using `module.exports`) we can ensure that state is not shared accidentally, and the regex is not compiled until it's needed.
